# Echo-Port Scanner
# Author: Haim Cohen
# LinkedIn: https://www.linkedin.com/in/haimc/
# GitHub: https://github.com/sk3pp3r/echo-port-scanner/

name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag echo-port-scanner:$(date +%s)
      
    - name: Run security scan
      uses: anchore/scan-action@v2
      with:
        image: "echo-port-scanner:latest"
        fail-build: true 